### ISSUE TITLE
Just for demo or mistake?

### ISSUE THREAD

**Issue by javierztl** [icoz69/HDN#3]
According to the paper, the level here https://github.com/icoz69/HDN/blob/df9bb5feb9253bec29511b72dc39d63d57ec9d19/demo.py#L172 and https://github.com/icoz69/HDN/blob/df9bb5feb9253bec29511b72dc39d63d57ec9d19/demo.py#L173 should be 2?

**Comment by icoz69** [comment]
hi, it doesn't matter. the optimal hyper-parameters may vary
